root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/go-htmx ./cmd/go-htmx"
  entrypoint = "./tmp/go-htmx"
  include_ext = ["go", "html", "css", "js"]
  exclude_dir = ["tmp"]
  exclude_regex = ["_test\\.go"]
  delay = 200

[log]
  time = false

[proxy]
  enabled = true
  proxy_port = 8090
  app_port = 8080

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[misc]
  clean_on_exit = true